version: "3.9"

services:
  pizza-hub:
    container_name: pizza-hub-container
    build:
      network: host
      context: ./
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - "3000:3005"
    env_file:
      - .env
    network_mode: "host"
